apiVersion: apps/v1
kind: Deployment
metadata:
  name: etherpad
  labels:
    app: etherpad
spec:
  selector:
    matchLabels:
      app: etherpad
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: etherpad
    spec:
      containers:
        - image: etherpad/etherpad:latest
          name: etherpad
          env:
            - name: PORT
              value: '9001'
            - name: NODE_ENV
              value: production
            - name: DB_TYPE
              value: mysql
            - name: DB_USER
              value: etherpad
            - name: DB_NAME
              value: etherpad
            - name: DB_HOST
              value: mysql
            - name: DB_CHARSET
              value: utf8mb4
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: etherpad
                  key: mysql_etherpad_password

          ports:
            - containerPort: ${SERVER_PORT}
              name: etherpad