apiVersion: v1
kind: Service
metadata:
  name: etherpad
  labels:
    app: etherpad
spec:
  type: ClusterIP
  ports:
    - name: port
      targetPort: 9001
      port: 80
      protocol: TCP
  selector:
    app: etherpad